List<Map<String, dynamic>> drinkData = [
  {
    'id' : 0,
    'proName' : 'Coca-Cola',
    'qty' : 0,
    'unitPrice' : 2,
    'imageUrl' : 'https://images2.minutemediacdn.com/image/upload/c_fill,g_auto,h_740,w_1100/v1555172501/shape/mentalfloss/iStock-487787108.jpg?itok=B3m9QDQG',
  },
  {
    'id' : 1,
    'proName' : 'Fanta',
    'qty' : 0,
    'unitPrice' : 2.5,
    'imageUrl' : 'https://previews.123rf.com/images/cookelma/cookelma1405/cookelma140500103/28360818-moscow-russia-april-4-2014-can-of-coca-cola-company-soft-drink-fanta-orange-on-ice-fanta-is-a-global.jpg',
  },
  {
    'id' : 2,
    'proName' : 'Dasani',
    'qty' : 0,
    'unitPrice' : 4,
    'imageUrl' : 'https://media.gettyimages.com/photos/tub-filled-with-ice-and-bottles-of-dasani-drinking-water-at-a-fourth-picture-id817054242',
  },
  {
    'id' : 3,
    'proName' : 'Bacchus',
    'qty' : 0,
    'unitPrice' : 2.1,
    'imageUrl' : 'https://vision.turnkeygroup.co/wp-content/uploads/2019/10/bacchus.jpg',
  },
  {
    'id' : 4,
    'proName' : 'Carabao',
    'qty' : 0,
    'unitPrice' : 3.6,
    'imageUrl' : 'https://image.shutterstock.com/image-photo/klangmalaysia-circa-october-2020-picture-260nw-1840163848.jpg',
  },
  {
    'id' : 5,
    'proName' : 'Angkor',
    'qty' : 0,
    'unitPrice' : 6,
    'imageUrl' : 'https://live.staticflickr.com/4068/4648875850_94f9696e18_b.jpg',
  },
  {
    'id' : 6,
    'proName' : 'ABC',
    'qty' : 0,
    'unitPrice' : 34,
    'imageUrl' : 'https://d3nuqriibqh3vw.cloudfront.net/styles/aotw_card_ir/s3/abc_photography_poster_iceblock_fa_aotw.jpg?itok=sZL149BV',
  },
  {
    'id' : 7,
    'proName' : 'Pocari',
    'qty' : 0,
    'unitPrice' : 4.2,
    'imageUrl' : 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcThl9yqZ5dT6Sw4nh-k1pCBSPhhIo_f9R0vidlqSFHQhjVqo3TbjSiO9RoltL3NWX1R0&usqp=CAU',
  },
  {
    'id' : 8,
    'proName' : 'Sprite',
    'qty' : 0,
    'unitPrice' : 2.5,
    'imageUrl' : 'https://previews.123rf.com/images/cookelma/cookelma1405/cookelma140500113/28360828-moscow-russia-april-4-2014-can-of-coca-cola-company-soft-drink-sprite-on-ice-it-was-introduced-in-th.jpg',
  },
  {
    'id' : 9,
    'proName' : 'Pepsi',
    'qty' : 0,
    'unitPrice' : 5.2,
    'imageUrl' : 'https://i.pinimg.com/originals/36/9f/b1/369fb16d87c7a113d99b86a5b37c7f1f.jpg',
  },
];

List<Map<String, dynamic>> popCornData = [
  {
    'id' : 10,
    'proName' : 'Dent',
    'qty' : 0,
    'unitPrice' : 6.3,
    'imageUrl' : 'https://i2.wp.com/www.spainonafork.com/wp-content/uploads/2019/04/popcornHOR-11.png?fit=750%2C750&ssl=1',
  },
  {
    'id' : 11,
    'proName' : 'Sweet',
    'qty' : 0,
    'unitPrice' : 3.5,
    'imageUrl' : 'https://www.rachelpaulsfood.com/wp-content/uploads/DSC_0697.jpg',
  },
  {
    'id' : 12,
    'proName' : 'Hominy',
    'qty' : 0,
    'unitPrice' : 5.3,
    'imageUrl' : 'https://nypost.com/wp-content/uploads/sites/2/2020/09/popcorn.jpg?quality=80&strip=all&w=1200',
  },
  {
    'id' : 13,
    'proName' : 'Mushroom',
    'qty' : 0,
    'unitPrice' : 2.4,
    'imageUrl' : 'https://d47gxy3fatgwk.cloudfront.net/wp-content/uploads/2019/01/5-minute-cheddar-cheese-popcorn-225.jpg',
  },
  {
    'id' : 14,
    'proName' : 'Snowstorm',
    'qty' : 0,
    'unitPrice' : 5.1,
    'imageUrl' : 'https://cdn-aiapl.nitrocdn.com/KZJKWDkEwMJCwERIlnRsPNdqobwBIlEo/assets/static/optimized/rev-e0253d2/wp-content/uploads/2012/11/Microwave-Caramel-Popcorn-8.jpg',
  },
  {
    'id' : 14,
    'proName' : 'First Born',
    'qty' : 0,
    'unitPrice' : 4.2,
    'imageUrl' : 'https://ichef.bbci.co.uk/food/ic/food_16x9_832/recipes/curry_and_lime-spiced_58305_16x9.jpg',
  },
  {
    'id' : 16,
    'proName' : 'Pimp My',
    'qty' : 0,
    'unitPrice' : 4.5,
    'imageUrl' : 'https://charlotteslivelykitchen.com/wp-content/uploads/2017/02/Popcorn-3.jpg',
  },
  {
    'id' : 17,
    'proName' : 'Stovetop',
    'qty' : 0,
    'unitPrice' : 5.2,
    'imageUrl' : 'https://cdn1.thepopcornfactory.com/wcsstore/ThePopcornFactory/images/catalog/tpf_68089x.jpg',
  },
  {
    'id' : 18,
    'proName' : 'Kettle',
    'qty' : 0,
    'unitPrice' : 3.5,
    'imageUrl' : 'https://assets.tmecosys.com/image/upload/t_web767x639/img/recipe/ras/Assets/76415C5D-3E4B-4D7C-A77B-7382589AAF1A/Derivates/15711463-5d0a-42f5-91b8-64435e757c09.jpg',
  },
  {
    'id' : 19,
    'proName' : 'Snackers',
    'qty' : 0,
    'unitPrice' : 1.5,
    'imageUrl' : 'https://www.yourhomebasedmom.com/wp-content/uploads/2020/11/Christmas-Popcorn-6-of-6.jpg',
  },
];

List<Map<String, dynamic>> iceCreamData = [
  {
    'id' : 20,
    'proName' : 'Banana',
    'qty' : 0,
    'unitPrice' : 5.3,
    'imageUrl' : 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Ice_cream_with_whipped_cream%2C_chocolate_syrup%2C_and_a_wafer_%28cropped%29.jpg/1200px-Ice_cream_with_whipped_cream%2C_chocolate_syrup%2C_and_a_wafer_%28cropped%29.jpg',
  },
  {
    'id' : 21,
    'proName' : 'Split',
    'qty' : 0,
    'unitPrice' : 6.4,
    'imageUrl' : 'https://laurenslatest.com/wp-content/uploads/2020/08/vanilla-ice-cream-5-copy.jpg',
  },
  {
    'id' : 22,
    'proName' : 'Birthday',
    'qty' : 0,
    'unitPrice' : 4.3,
    'imageUrl' : 'https://www.thespruceeats.com/thmb/BYOHKcXhja-ez7Fr9obgBrDHJ1Y=/3064x2042/filters:fill(auto,1)/easy-chocolate-ice-cream-recipe-1945798-hero-01-45d9f26a0aaf4c1dba38d7e0a2ab51e2.jpg',
  },
  {
    'id' : 23,
    'proName' : 'Berry',
    'qty' : 0,
    'unitPrice' : 5.1,
    'imageUrl' : 'https://littlefaifo.com/wp-content/uploads/2021/03/ourstory_012-6.jpg',
  },
  {
    'id' : 24,
    'proName' : 'Bubble',
    'qty' : 0,
    'unitPrice' : 4.2,
    'imageUrl' : 'https://barefeetinthekitchen.com/wp-content/uploads/2018/05/Easiest-Ice-Cream-1-1-of-1-500x500.jpg',
  },
  {
    'id' : 25,
    'proName' : 'Bunny',
    'qty' : 0,
    'unitPrice' : 6.3,
    'imageUrl' : 'https://images.herzindagi.info/image/2020/Jun/chocolate-parle-g-ice-cream.jpg',
  },
  {
    'id' : 26,
    'proName' : 'Butter',
    'qty' : 0,
    'unitPrice' : 5.2,
    'imageUrl' : 'https://img.buzzfeed.com/buzzfeed-static/static/2015-08/20/16/enhanced/webdr04/original-9911-1440101165-11.jpg?downsize=700%3A%2A&output-quality=auto&output-format=auto',
  },
  {
    'id' : 27,
    'proName' : 'Tracks',
    'qty' : 0,
    'unitPrice' : 4.1,
    'imageUrl' : 'https://images.wsj.net/im-214963?width=1280&size=1',
  },
  {
    'id' : 28,
    'proName' : 'Carrot',
    'qty' : 0,
    'unitPrice' : 5.3,
    'imageUrl' : 'https://www.the-beatyard.com/wp-content/uploads/2017/05/fixedw_large_2x-1-612x540.jpg',
  },
  {
    'id' : 29,
    'proName' : 'Chocolate',
    'qty' : 0,
    'unitPrice' : 4.1,
    'imageUrl' : 'https://www.thespruceeats.com/thmb/RrP9qTWy2BbntDB6GCwWi8Yy29U=/3000x2000/filters:fill(auto,1)/UbeIceCreamHERO-ae953a4c3ede4690bd2f0ccbc104ea12.jpg',
  },
];

List<Map<String, dynamic>> discountData = [
  {
    'id' : 30,
    'proName' : 'RedBull',
    'qty' : 0,
    'unitPrice' : 5.3,
    'imageUrl' : 'https://i2-prod.mirror.co.uk/incoming/article9309511.ece/ALTERNATES/s1200c/Head-Teacher-bans-Energy-Drinks-at-School.jpg',
  },
  {
    'id' : 31,
    'proName' : 'Vigor',
    'qty' : 0,
    'unitPrice' : 3.1,
    'imageUrl' : 'https://images-platform.99static.com/BMF9D7wuiOv24eSZHMEGy1ze4do=/136x0:1889x1753/500x500/top/smart/99designs-contests-attachments/62/62732/attachment_62732419',
  },
  {
    'id' : 32,
    'proName' : 'Sting',
    'qty' : 0,
    'unitPrice' : 7.5,
    'imageUrl' : 'http://snlonlinegrocery.com/wp-content/uploads/2016/09/sting-energy-drink-330ml-deals.jpg',
  },
  {
    'id' : 33,
    'proName' : 'TATA Water',
    'qty' : 0,
    'unitPrice' : 4.1,
    'imageUrl' : 'https://miro.medium.com/max/1200/1*Y3dDhDc0CTZ_Ebnsga3K6Q.jpeg',
  },
  {
    'id' : 34,
    'proName' : 'Caramel',
    'qty' : 0,
    'unitPrice' : 4.2,
    'imageUrl' : 'https://storcpdkenticomedia.blob.core.windows.net/media/recipemanagementsystem/media/recipe-media-files/recipes/retail/x17/17244-caramel-topped-ice-cream-dessert-760x580.jpg?ext=.jpg',
  },
  {
    'id' : 35,
    'proName' : 'Vanilla',
    'qty' : 0,
    'unitPrice' : 4.4,
    'imageUrl' : 'https://www.seriouseats.com/2018/06/20180625-no-churn-vanilla-ice-cream-vicky-wasik-13-1500x1125.jpg',
  },
  {
    'id' : 36,
    'proName' : 'Cookies',
    'qty' : 0,
    'unitPrice' : 1.5,
    'imageUrl' : 'https://www.davidlebovitz.com/wp-content/uploads/2020/05/Chocolate-chip-ice-cream-gelato-amaro-recipe_-9.jpg',
  },
  {
    'id' : 37,
    'proName' : 'Instant',
    'qty' : 0,
    'unitPrice' : 6.2,
    'imageUrl' : 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSf2492H9ERtzjfqlSQEkylvQYrvsfzt8FRGg&usqp=CAU',
  },
  {
    'id' : 37,
    'proName' : 'Dill',
    'qty' : 0,
    'unitPrice' : 4.1,
    'imageUrl' : 'https://kaynutrition.com/wp-content/uploads/2019/01/dill-pickle-popcorn-1.jpg',
  },
  {
    'id' : 39,
    'proName' : 'Cheddar',
    'qty' : 0,
    'unitPrice' : 6.3,
    'imageUrl' : 'https://feastandwest.com/wp-content/uploads/2020/06/homemade-cheddar-cheese-popcorn-photo.jpg',
  },
];